version: '3'
tasks:
  run:
    cmds:
      - go run src/main/main.go
  gen-proto:
    cmds:
      - rm -rf src/main/gen/*
      - >
        protoc --go_out=src/main/gen --go-grpc_out=src/main/gen --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative src/main/proto/*.proto
        --go_opt=Msrc/main/proto/external-service.proto=github.com/DuongVu98/grpcdemo/src/main/gen